[env:lower_test]
platform = ststm32
board = genericSTM32F103CB
board_build.mcu = stm32f103cbt6
framework = arduino
upload_protocol = stlink

build_flags =
    -DHAL_CAN_MODULE_ENABLED
    -DHSE_VALUE=16000000U
    -Wall
    -Wextra
    -Werror
    -fno-exceptions
    -Wno-error=unused-parameter
    -Wno-error=unused-variable

monitor_filters = send_on_enter

lib_extra_dirs = ../libraries     
lib_ldf_mode = deep+